version: '3.7'

services:
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3100:3100"
      - "9411:9411"
      - "14268:14268"
      #- "4317:4317"
      - "4318:4318"
    volumes:
      - ./tempo-data:/var/lib/tempo
    command: ["-config.file=/etc/tempo.yaml"]
    configs:
      - source: tempo-config
        target: /etc/tempo.yaml
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - monitoring-network

configs:
  tempo-config:
    file: ./tempo.yaml

networks:
  monitoring-network:
    driver: bridge
